name: S3

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: smoke test
        run: aws s3 ls s3://mp33-test/meta/
