name: S3

on:
  workflow_dispatch:

jobs:
  build_and_deply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: smoke test
        run: aws --endpoint "${AWS_S3_ENDPOINT}" s3 ls s3://mp33-test/meta/
