name: S3

on:
  workflow_dispatch:

jobs:
  build_and_deply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: smoke test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: aws --endpoint "${{ secrets.AWS_S3_ENDPOINT }}" s3 ls s3://mp33-test/meta/
