name: Docker build and push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag name'     
        required: true
        default: 'test'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "quay.io/prete/dumpster-fire:${{ github.event.inputs.tag }}" 
