name: Build and push docker image

on:
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v2

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: quay.io/prete/dumpster-fire:latest
