name: basic commands

on:
  workflow_dispatch:

jobs:

  test:  
    name: commands
    
    runs-on: self-hosted

    steps:
    
      - name: checkout
        uses: actions/checkout@master

      - name: list files
        run: ls $GITHUB_WORKSPACE

      - name: remove
        run: rm -rf $GITHUB_WORKSPACE/*
        
      - name: list files
        run: ls $GITHUB_WORKSPACE
