name: Show github conetxt and env

on:
  workflow_dispatch:
  
jobs:

  github_ctx_env:
  
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Inspect 'github' context
        run: |
          echo "github.action:           ${{ github.action }}"
          echo "github.action_path:      ${{ github.action_path }}"
          echo "github.actor:            ${{ github.actor  }}"
          echo "github.base_ref:         ${{ github.base_ref }}"
          echo "github.event_name:       ${{ github.event_name }}"
          echo "github.event_path:       ${{ github.event_path }}"
          echo "github.head_ref:         ${{ github.head_ref }}"
          echo "github.job:              ${{ github.job }}"
          echo "github.ref:              ${{ github.ref }}"
          echo "github.repository:       ${{ github.repository }}"
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.run_id:           ${{ github.run_id }}"
          echo "github.run_number:       ${{ github.run_number }}"
          echo "github.sha:              ${{ github.sha }}"

      - name: Inspect 'GITHUB_' environment
        run: |
          echo "GITHUB_WORKFLOW:   ${GITHUB_WORKFLOW}"
          echo "GITHUB_RUN_ID:      ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER:  ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_JOB:         ${GITHUB_JOB}"
          echo "GITHUB_ACTION:      ${GITHUB_ACTION}"
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          echo "GITHUB_ACTIONS:     ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR:       ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY:  ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME:  ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH:  ${GITHUB_EVENT_PATH}"
          echo "GITHUB_WORKSPACE:   ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA:         ${GITHUB_SHA}"
          echo "GITHUB_REF:         ${GITHUB_REF}"
          echo "GITHUB_HEAD_REF:    ${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF:    ${GITHUB_BASE_REF}"
          echo "GITHUB_SERVER_URL:  ${GITHUB_SERVER_URL}"
          echo "GITHUB_API_URL:     ${GITHUB_API_URL}"
          echo "GITHUB_GRAPHQL_URL: ${GITHUB_GRAPHQL_URL}"
          echo "RUNNER_OS:          ${RUNNER_OS}"
          echo "RUNNER_TEMP:        ${RUNNER_TEMP}"
          echo "RUNNER_TOOL_CACHE:  ${RUNNER_TOOL_CACHE}"

      - name: Extract branch name
        id: git
        run: |
          echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Show branch name
        run: |   
          echo "${{ steps.git.outputs.branch_name }}"
