name: 🐻

on:
  workflow_dispatch:

jobs:

  test:  
    name: rcone mount
    
    runs-on: ubuntu-latest

    steps:
      - name: install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: configure rclone for s3 
        run: rclone config create s3 s3 \
          env_auth false \
          region other-v2-signature \
          access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} \
          secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          endpoint ${{ secrets.AWS_S3_ENDPOINT }}

      - name: mount s3 storage and so something
        run: |
          mkdir -p "$GITHUB_WORKSPACE/s3"
          rclone mount s3:mp33 "$GITHUB_WORKSPACE/s3" --daemon --allow-other --allow-non-empty
          ls "$GITHUB_WORKSPACE/s3"
          rclone lsf s3:mp33
