name: build-course

on:
  workflow_dispatch:

jobs:

  build-course:  
    name: Build scRNAseq-course
    
    runs-on: ubuntu-latest
    container:
      image: quay.io/cellgeni/scrna-seq-course:v5.11
      options: --user root

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: other-v2-signature

    steps:      
      - name: Disk space report before modification
        shell: bash
        run: |
          echo "Memory and swap:"
          free
          echo
          swapon --show
          echo
          echo "Available storage:"
          df -h
          echo

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve course data from S3
        run: |
          mkdir -p $GITHUB_WORKSPACE/data
          aws s3 sync s3://mp33/course/data/ $GITHUB_WORKSPACE/data --endpoint-url ${{ secrets.AWS_S3_ENDPOINT }}

      - name: Retrieve bookdown cache from S3
        run: |
          mkdir -p $GITHUB_WORKSPACE/_bookdown_files
          aws s3 sync s3://mp33/course/_bookdown_files/ $GITHUB_WORKSPACE/_bookdown_files --endpoint-url ${{ secrets.AWS_S3_ENDPOINT }}
          
      - name: Render bookdown Rmd files for site generation
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          mkdir /course
          cp -r $GITHUB_WORKSPACE/course_files/* /course
          rm -rf $GITHUB_WORKSPACE/course_files
          mv $GITHUB_WORKSPACE/_bookdown_files /course
          mv $GITHUB_WORKSPACE/data /course
          cd /course
          Rscript -e "bookdown::render_book('index.html', 'bookdown::gitbook')"
          mv /course/website $GITHUB_WORKSPACE
          mv /course/_bookdown_files $GITHUB_WORKSPACE
        
      - name: Upload rendered bookdown files to S3
        run: aws s3 sync $GITHUB_WORKSPACE/website s3://mp33/course/website/ --endpoint-url ${{ secrets.AWS_S3_ENDPOINT }}
        
      - name: Upload bookdown cache to S3
        run: aws s3 sync $BUILD_DIR/_bookdown_files s3://mp33/course/_bookdown_files/ --endpoint-url ${{ secrets.AWS_S3_ENDPOINT }}
        
